controllers:
    resource: ../src/Controller/
    type: attribute

index: 
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::index' }

lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::numberAction

blog_list_twig:
    path:     /blogtwig
    controller: App\Controller\BlogTwigController::list

blog_show_twig:
    path:     /blogtwig/{entryId}
    controller: App\Controller\BlogTwigController::show